config/routes.rb
PrivilegedSessions::Application.routes.draw do
  resources :privileged_sessions, only: [:new, :create] do
    collection { delete :destroy }
  end

  devise_for :users, controllers: { registrations: 'registrations' }

  root to: 'high_voltage/pages#show', id: 'home'
end

app/models/privileged_session.rb
class PrivilegedSession < ActiveRecord::Base
  belongs_to :user

  LIFESPAN = Integer(ENV['PRIVILEGE_LIFESPAN'] || 60)

  scope :active,   ->{ where("created_at > ? AND revoked_at IS ?", LIFESPAN.minutes.ago, nil) }
  scope :inactive, ->{ where("created_at < ? OR revoked_at IS NOT ?", LIFESPAN.minutes.ago, nil) }

  before_validation :set_unique_key, on: :create

  private

  def set_unique_key
    self.key = SecureRandom.urlsafe_base64(32)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :privileged_sessions

  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable

  def privileged?(key)
    return false unless key.present?
    !!privileged_sessions.active.exists?(key: key)
  end

  def revoke_privilege!(key)
    privileged_sessions.where(key: key).update_all(revoked_at: Time.now)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :privileged?

  private

  def require_privilege!
    unless privileged?
      session[:redirect_to_privileged] = request.path
      flash[:warning] = I18n.t('privileged_session.failure.privilege_required')
      redirect_to new_privileged_session_path
    end
  end

  def privileged?
    return @_privileged if defined?(@_privileged)
    @_privileged = user_signed_in? && current_user.privileged?(session[:privileged_session_key])
  end
end

app/controllers/privileged_sessions_controller.rb
class PrivilegedSessionsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_no_privilege!, except: [:destroy]
  before_action :require_privilege!, only: [:destroy]

  def new
  end

  def create
    if current_user.valid_password?(user_password)
      session[:privileged_session_key] = current_user.privileged_sessions.create.key
      redirect_to session[:redirect_to_privileged] || root_path,
        notice: I18n.t('privileged_session.success.privilege_enabled', minutes: PrivilegedSession::LIFESPAN)
    else
      flash[:error] = I18n.t('privileged_session.failure.invalid_password')
      render :new
    end
  end

  def destroy
    current_user.revoke_privilege!(session[:privileged_session_key])
    redirect_to root_path, notice: I18n.t('privileged_session.success.privilege_revoked')
  end

  private

  def user_password
    params[:user] && params[:user][:password]
  end

  def require_no_privilege!
    if privileged?
      redirect_to root_path, notice: I18n.t('privileged_session.failure.already_privileged')
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :require_privilege!, except: [:new, :create]
end

app/helpers/application_helper.rb
module ApplicationHelper
  FLASH_CLASSES = {
    alert: "danger",
    error: "danger",
    notice: "success",
  }.with_indifferent_access.freeze

  def flash_class(name)
    FLASH_CLASSES[name] || name
  end

  def navbar_list_item(text, options={})
    return if options.delete(:hide)
    render 'navbar_list_item', text: text, path: yield, options: options
  end
end

app/views/application/_flashes.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= flash_class(name) %>" data-dismiss="alert">
    <%= msg %>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

<% if GAUGES_SITE_ID %>
<script type="text/javascript">
  var _gauges = _gauges || [];
  (function() {
    var t   = document.createElement('script');
    t.type  = 'text/javascript';
    t.async = true;
    t.id    = 'gauges-tracker';
    t.setAttribute('data-site-id', '<%= GAUGES_SITE_ID %>');
    t.src = '//secure.gaug.es/track.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(t, s);
  })();
</script>
<% end %>

app/views/application/_navbar.html.erb
<div class="container">
  <div class="navbar navbar-default">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Privileged Sessions', root_path, class: 'navbar-brand' %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <%= navbar_list_item('Home') { root_path } %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= navbar_list_item('Sign up', hide: user_signed_in?) { new_user_registration_path } %>
        <%= navbar_list_item('Sign in', hide: user_signed_in?) { new_user_session_path } %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <%= link_to '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' } do %>
              <%= current_user.email %> <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <%= navbar_list_item('Account', hide: !user_signed_in?) { edit_user_registration_path } %>
              <%= navbar_list_item('Revoke Privilege', hide: !privileged?, method: :delete) { privileged_sessions_path } %>
              <%= navbar_list_item('Sign out', hide: !user_signed_in?, method: :delete) { destroy_user_session_path } %>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/application/_navbar_list_item.html.erb
<li class="<%= current_page?(path) ? 'active' : '' %>">
  <%= link_to text, path, {title: text}.merge(options) %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Privileged Sessions</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'navbar' %>
  <div class="container">
    <%= render 'flashes' %>
    <%= yield %>
  </div>
  <%= render 'javascript' %>
  <a href="https://github.com/invisiblefunnel/privileged-sessions-app"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png" alt="Fork me on GitHub"></a>
</body>
</html>

app/views/pages/home.html.erb
<div class="well">
  <h3>Privileged Sessions</h3>

  <p>
    Based on <a href="https://github.com/blog/1661-modeling-your-app-s-user-session">https://github.com/blog/1661-modeling-your-app-s-user-session</a>.
  </p>

  <p>Feel free to <%= link_to 'sign up', new_user_registration_path %> with a fake email address and try it out.</p>
</div>

app/views/privileged_sessions/new.html.erb
<%= simple_form_for :user, url: privileged_sessions_path, html: { class: 'form-narrow' } do |f| %>
  <div class="form-narrow-heading">
    <h2>Enable Privileged Mode</h2>
  </div>
  <%= f.input :password, as: :password, autofocus: true %>
  <%= f.button :submit, value: 'Enable' %>
<% end %>